Import the numpy module

In [1]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [8]:
list = [ 3,  6,  9, 12, 15]
arr1 = np.array(list)
arr1

array([ 3,  6,  9, 12, 15])

Print out the 3rd element of the array.

In [6]:
arr1[2]

9

Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [9]:
list = [[ 2,  4,  6],[ 3,  6,  9],[ 4,  8, 12]]
arr2 = np.array(list)
arr2

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

Print out the element at row=3,col=2.

In [12]:
arr2[2][1]

8

Create an array that goes from 0 to 100 with step=3. Display it.

In [15]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Create a 10x5 2d array filled with zeroes. Display it.

In [18]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [22]:
lin1d = np.linspace(57,108,100)
lin1d

array([ 57.        ,  57.51515152,  58.03030303,  58.54545455,
        59.06060606,  59.57575758,  60.09090909,  60.60606061,
        61.12121212,  61.63636364,  62.15151515,  62.66666667,
        63.18181818,  63.6969697 ,  64.21212121,  64.72727273,
        65.24242424,  65.75757576,  66.27272727,  66.78787879,
        67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
        69.36363636,  69.87878788,  70.39393939,  70.90909091,
        71.42424242,  71.93939394,  72.45454545,  72.96969697,
        73.48484848,  74.        ,  74.51515152,  75.03030303,
        75.54545455,  76.06060606,  76.57575758,  77.09090909,
        77.60606061,  78.12121212,  78.63636364,  79.15151515,
        79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
        81.72727273,  82.24242424,  82.75757576,  83.27272727,
        83.78787879,  84.3030303 ,  84.81818182,  85.33333333,
        85.84848485,  86.36363636,  86.87878788,  87.39393939,
        87.90909091,  88.42424242,  88.93939394,  89.45

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [25]:
lin2d = lin1d.reshape(10,10)
lin2d

array([[ 57.        ,  57.51515152,  58.03030303,  58.54545455,
         59.06060606,  59.57575758,  60.09090909,  60.60606061,
         61.12121212,  61.63636364],
       [ 62.15151515,  62.66666667,  63.18181818,  63.6969697 ,
         64.21212121,  64.72727273,  65.24242424,  65.75757576,
         66.27272727,  66.78787879],
       [ 67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
         69.36363636,  69.87878788,  70.39393939,  70.90909091,
         71.42424242,  71.93939394],
       [ 72.45454545,  72.96969697,  73.48484848,  74.        ,
         74.51515152,  75.03030303,  75.54545455,  76.06060606,
         76.57575758,  77.09090909],
       [ 77.60606061,  78.12121212,  78.63636364,  79.15151515,
         79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
         81.72727273,  82.24242424],
       [ 82.75757576,  83.27272727,  83.78787879,  84.3030303 ,
         84.81818182,  85.33333333,  85.84848485,  86.36363636,
         86.87878788,  87.39393939],
       [ 8

Print out the shape of lin1d and lin2d.

In [29]:
print('lin1d: ',lin1d.shape)
print('lin2d: ',lin2d.shape)

lin1d:  (100,)
lin2d:  (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [111]:
nums = np.random.rand(5,5)
nums

array([[0.19513361, 0.42733971, 0.37785202, 0.5224612 , 0.93504198],
       [0.60698676, 0.24291678, 0.34001448, 0.6540702 , 0.42147999],
       [0.60373909, 0.0900258 , 0.42523894, 0.01322022, 0.41622718],
       [0.95984712, 0.41914982, 0.50678715, 0.29464479, 0.67343198],
       [0.16343579, 0.83673798, 0.4262682 , 0.52174445, 0.72763918]])

Print out the min, max and mean of the nums array.

In [112]:
print('Min: ',nums.min())
print('Max: ',nums.max())
print('Mean: ',nums.mean())

Min:  0.013220217628921671
Max:  0.9598471161112266
Mean:  0.47205737718185864


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [113]:
nums = nums * 2
nums

array([[0.39026722, 0.85467943, 0.75570405, 1.04492239, 1.87008396],
       [1.21397351, 0.48583356, 0.68002897, 1.30814041, 0.84295998],
       [1.20747819, 0.18005161, 0.85047788, 0.02644044, 0.83245436],
       [1.91969423, 0.83829964, 1.0135743 , 0.58928957, 1.34686396],
       [0.32687158, 1.67347595, 0.85253641, 1.04348891, 1.45527837]])

Select rows 1 to 2 and cols 2 to 3 and display the result.

In [114]:
nums[1:3,2:4]

array([[0.68002897, 1.30814041],
       [0.85047788, 0.02644044]])

Modify that same selection by multiplying it x10, then display the new nums array.

In [115]:
nums[1:3,2:4] *= 10
nums

array([[ 0.39026722,  0.85467943,  0.75570405,  1.04492239,  1.87008396],
       [ 1.21397351,  0.48583356,  6.80028967, 13.0814041 ,  0.84295998],
       [ 1.20747819,  0.18005161,  8.50477878,  0.26440435,  0.83245436],
       [ 1.91969423,  0.83829964,  1.0135743 ,  0.58928957,  1.34686396],
       [ 0.32687158,  1.67347595,  0.85253641,  1.04348891,  1.45527837]])